GET http://localhost:3000/tablas

###

GET http://localhost:3000/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdHV0ZXJvbmNvIiwiaWF0IjoxNzIyOTUzODMwLCJleHAiOjE3MjI5NTU2MzB9.fzOxxrSDaND-_yDNsi35XUiB8JMDCPINxHYls4oJeeE

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "usernameEmail": "JaquelinWasky",
    "password": "hola"
}

###

POST http://localhost:3000/auth/test
Content-Type: application/json

{
    "email": "luquitavo@gmail.com"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "JoseIngeniero",
    "email": "jose@gmail.com",
    "name": "Luca",
    "surname": "Chami",
    "password": "5050",
    "confirmPassword": "5050"
}

###

POST http://fraktalapi.vercel.app/auth/register
Content-Type: application/json

{
    "username": "manuel",
    "email": "paja@gmail.com",
    "name": "Luca",
    "surname": "Chami",
    "password": "5050",
    "confirmPassword": "5050"
}

###

GET http://localhost:3000/auth/token
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphcXVlbGluV2Fza3kiLCJpYXQiOjE3MjQ2Nzc3MDQsImV4cCI6MTcyNDY3OTUwNH0.voXHYNHa0y8dliTfWH8G_nFZBzyiSROfO0CICn0XlKc

###

DELETE http://localhost:3000/auth/logout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdHV0ZXJvbmNvIiwiaWF0IjoxNzIyOTUwNjIyLCJleHAiOjE3MjMwMzcwMjJ9.mwU2xsKF6S9_3-NUp5DTFCZ86dH7NnUmHPAVsoy-DoU

###

DELETE http://localhost:3000/auth/deleteAccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdHV0ZXJvbmNvIiwiaWF0IjoxNzIyOTU0NjM0LCJleHAiOjE3MjI5NTY0MzR9.l7JtciDkvpsOYs_Tiw8ShEgfKw3U44cH_KTQrH8-0tE
Content-Type: application/json

{
    "password": "5050"
}

###

POST http://192.168.32.67:3000/hist/
Content-Type: application/json

{
    "hola": "hla"
}

###

GET http://localhost:3000/hist/tabla

###

GET http://localhost:3000/hist/card

###

GET http://localhost:3000/hist/card/finger-print

###

POST http://localhost:3000/hist/card/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uZXNjb2xhckBnbWFpbC5jb20iLCJpYXQiOjE3MDExNjg0MzcsImV4cCI6MTcwMTE3OTIzN30.5wM08fw413oDFxkgpqSeYaUhJaffgw4QQ3VBqKQdYEY
Content-Type: application/json

{
    "id": "2",
    "name": "Mati",
    "surname": "Buñes",
    "isFingerPrint": true
}

###

DELETE http://localhost:3000/hist/card/delete
Content-Type: application/json

{
    "id": "23D92382"
}

###

GET http://localhost:3000/hist/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uZXNjb2xhckBnbWFpbC5jb20iLCJpYXQiOjE3MDExNjg0MzcsImV4cCI6MTcwMTE3OTIzN30.5wM08fw413oDFxkgpqSeYaUhJaffgw4QQ3VBqKQdYEY

###

POST http://localhost:3000/hist/register/create
Content-Type: application/json

{
    "idCard": "8D08718B",
    "ownerEmail": "simonescolar@gmail.com"
    //"description": "ingreso"
}

###

POST http://localhost:3000/hist/register/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uZXNjb2xhckBnbWFpbC5jb20iLCJpYXQiOjE3MDExNzEwOTksImV4cCI6MTcwMTE4MTg5OX0.t7m3cNS9No9MiI2FjWUXvEBDITYoI6zeXPyABjyoWkQ
Content-Type: application/json

{
    "id": 206
}

###

POST http://localhost:3000/hist/register/video
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uZXNjb2xhckBnbWFpbC5jb20iLCJpYXQiOjE3MDExNzEwOTksImV4cCI6MTcwMTE4MTg5OX0.t7m3cNS9No9MiI2FjWUXvEBDITYoI6zeXPyABjyoWkQ
Content-Type: application/json

{
    "id": 222
}